### ISSUE TITLE
Font not resolved - especially those lovely glyphs

### ISSUE THREAD

**Issue by fish-sm** [pvblicltd/Generator-CppAng#1]
Here's a screen shot of the 404's - you can work out the context root for my angular app (hosted in a war.... yikes....) - as you can see there's a few ../.. and ../ in the generated references and some stuff that maybe should be copied into dist??
![screen shot 2015-06-25 at 14 18 05](https://cloud.githubusercontent.com/assets/11871106/8355200/b663220e-1b45-11e5-84a9-fae91f6c17d0.png)

**Comment by pvblicltd** [comment]
I Steve I've updated the CPP.UI - if you do a "bower update" that should fix the font issues, just looking at the logo issue now

**Comment by pvblicltd** [comment]
Ok, I've fixed a couple off issues: 1. Assets folder now being added to the dist, and I found a bug when "modals" are generated that jshint was picking up - that's now fixed - Steve if you dont want to re-generate your app. 1. Change line 220 of the Gruntfile.js to this  from  {src: ['img/**'], dest: 'dist/'}, to {src: ['assets/**'], dest: 'dist/'},
